### ISSUE TITLE
Traceback Error While Importing Koohii Progression Anki Version 2.1.35 

### ISSUE THREAD

**Issue by maebutart** [Mauville/Koohii2Anki#14] opened 2020-11-26 16:44 UTC
Similarly to someone elses issue, I get greeted with a Traceback Error while trying to import my Koohii progression. Unlike them, I don't know how to fix it. 

![Traceback Error](https://user-images.githubusercontent.com/75088408/100375977-4f017580-2fd4-11eb-9df7-92b69b6b51f2.PNG)

Any help would be appreciated

**Comment by ur-miri** [comment] 2021-02-20 20:29
Duplicate of #14

**Comment by Mauville** [comment] 2021-03-31 02:48
Solved on #13

**Closed by Mauville** 2021-03-31 02:48 UTC
